# Generated by Django 4.1.3 on 2022-11-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='article',
            name='release_date',
        ),
    ]
